[package]
name = "bertrand"
version = "0.1.1"
edition = "2021"
description = "A dead-simple demo system for backend prototypes."
license-file = "LICENSE"
homepage = "https://github.com/arctic-hen7/bertrand"
repository = "https://github.com/arctic-hen7/bertrand"
readme = "README.md"

[dependencies]
anyhow = "1"
axum = { version = "0.7.7", features = [ "ws" ] }
clap = { version = "4.5.20", features = ["derive"] }
tokio = { version = "1.41.0", features = [ "macros", "rt-multi-thread", "fs" ] }
tower-http = { version = "0.6.1", features = ["fs"] }
